# Generated by Django 3.2.12 on 2022-03-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='genres',
        ),
    ]
