# Generated by Django 3.2.12 on 2022-03-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_delete_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='genres',
            fields=[
                ('song', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
    ]
